# Generated by Django 3.1.2 on 2020-12-27 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Size',
                'ordering': ['size_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Type',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(help_text='(max = 100 character)', max_length=100)),
                ('figure1', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('figure2', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('size', models.ManyToManyField(to='artikel.Size')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artikel.type')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Name',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstanceProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Code')),
                ('production_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artikel.product', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Stock Log',
                'verbose_name_plural': 'Stock Log',
                'ordering': ['production_date'],
            },
        ),
    ]
