# Generated by Django 3.1.2 on 2020-12-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstanceProduct',
            new_name='StockLog',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'type'], 'verbose_name': 'Name', 'verbose_name_plural': 'Name'},
        ),
        migrations.AlterModelOptions(
            name='stocklog',
            options={'ordering': ['production_date', 'product', 'quantity', 'price', 'sold'], 'verbose_name': 'Stock Log', 'verbose_name_plural': 'Stock Log'},
        ),
    ]
