# Generated by Django 3.1.2 on 2020-12-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_auto_20201228_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'type'], 'verbose_name': 'Name', 'verbose_name_plural': 'Name'},
        ),
        migrations.AlterModelOptions(
            name='stocklog',
            options={'ordering': ['production_date', 'product', 'quantity', 'price', 'sold'], 'verbose_name': 'Stock Log', 'verbose_name_plural': 'Stock Log'},
        ),
    ]
