# Generated by Django 3.1.2 on 2020-12-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_auto_20201231_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
