# Generated by Django 3.1.2 on 2020-12-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0006_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
