# Generated by Django 3.1.2 on 2020-12-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0007_type_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
