# Generated by Django 3.1.2 on 2020-12-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0009_auto_20201231_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='figure1',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='figure2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
