# Generated by Django 3.1.2 on 2020-12-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0010_auto_20201231_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
