# Generated by Django 3.1.2 on 2021-01-01 06:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0015_auto_20201231_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awareness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description', models.TextField(help_text='(max = 100 character)', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
