# Generated by Django 3.1.2 on 2021-01-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0017_remove_awareness_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awareness',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
