# Generated by Django 3.1.2 on 2021-01-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0018_auto_20210101_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awareness',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='awareness',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
